oidc:
  provider_url: "https://your-oidc-provider.com"
  client_id: "your-client-id"
  client_secret: "your-client-secret"

slack:
  token: "your-slack-bot-token"

tasks:
  - name: "Check Unused S3 Buckets"
    aws_accounts:
      - "123456789012"
      - "234567890123"
    service: "s3"
    command: "check_unused_buckets"
    schedule: "0 0 * * *"  # Run daily at midnight
    slack_channel: "#aws-notifications"

  - name: "List IAM Users"
    aws_accounts:
      - "123456789012"
      - "234567890123"
    service: "iam"
    command: "list_iam_users"
    schedule: "0 12 * * MON"  # Run every Monday at noon
    slack_channel: "#aws-notifications"