oidc:
  provider_url: "https://keycloak.rarefyconsulting.com/realms/master"
  client_id: "awsdevopsapi"
  client_secret: "Ceb2bGyg2KfPfE6JeY7J4oL37IcFE1AH"
  redirect_url: "http://localhost:8080/auth/callback"

slack:
  token: "your-slack-bot-token"

tasks:
  - name: "Check Unused S3 Buckets"
    aws_accounts:
      - "058264355882"
    service: "s3"
    command: "check_unused_buckets"
    schedule: "0 0 * * *" # Run daily at midnight
    slack_channel: "#aws-notifications"

  - name: "List IAM Users"
    aws_accounts:
      - "058264355882"
    service: "iam"
    command: "list_iam_users"
    schedule: "0 12 * * MON" # Run every Monday at noon
    slack_channel: "#aws-notifications"
